apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-task
spec:
  schedule: "0 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: check-task
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - curl -v todo-yuta-api-svc:3000/check/tasks
          restartPolicy: OnFailure