apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-batch
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-batch
            image: yutanishio0812/db-batch:latest
          restartPolicy: OnFailure