version: '3'
services:
  db:
    container_name: 'ytodo-db'
    build: .
    ports:
      - "15432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./:/work
    working_dir: /work