apiVersion: v1
kind: Service
metadata:
  labels:
    name: todo-yuta-api
  name: todo-yuta-api-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: todo-yuta-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-yuta-api
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: todo-yuta-api
  template:
    metadata:
      labels:
        name: todo-yuta-api
    spec:
      containers:
      - image: yutanishio0812/todo-yuta-api:latest
        name: todo-yuta-api
        ports:
          - containerPort: 3000
        