apiVersion: v1
kind: Service
metadata:
  labels:
    name: todo-yuta-web
  name: todo-yuta-web-svc
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    name: todo-yuta-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-yuta-web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: todo-yuta-web
  template:
    metadata:
      labels:
        name: todo-yuta-web
    spec:
      containers:
        - image: yutanishio0812/todo-yuta-web:latest
          name: todo-yuta-web
          ports:
            - containerPort: 3001
