apiVersion: v1
kind: Service
metadata:
  labels:
    name: ytodo-db
  name: ytodo-db-svc
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: ytodo-db
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytodo-db
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: ytodo-db
  template:
    metadata:
      labels:
        name: ytodo-db
    spec:
      containers:
      - image: yutanishio0812/ytodo-db:latest
        imagePullPolicy: Always
        name: ytodo-db
        ports:
          - containerPort: 5432
        