apiVersion: skaffold/v2beta24
kind: Config
build:
  artifacts:
    - image: yutanishio0812/todo-yuta-api
      context: ../../../todo-yuta-api
      docker:
        dockerfile: ../../../todo-yuta-api/Dockerfile
  local:
    push: false
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - ../../k8s/todo-yuta-api/k8s*
portForward:
  - resourceType: service
    resourceName: todo-yuta-api-svc
    port: 3000
    localPort: 3000
